name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lawanemoraes
          outputs: |
            dist/github-snake.svg?color_snake=#3B82F6&color_dots=#DBEAFE,#93C5FD,#60A5FA,#3B82F6,#1D4ED8
            dist/github-snake-dark.svg?color_snake=#60A5FA&color_dots=#172554,#1E40AF,#2563EB,#3B82F6,#60A5FA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output